name: build

on: push

jobs:
  build:
    runs-on: 'macos-14'

    steps:
      - name: Install dependencies
        run: brew install huggingface-cli

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Test
        run: |
          yarn
          huggingface-cli download mlx-community/Meta-Llama-3-8B-Instruct-4bit --local-dir weights-4bit
          echo Hello | node chat.js weights-4bit

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag
        run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set package version
        run: |
          npm config set git-tag-version=false
          npm version $VERSION

      - name: Install deps
        run: yarn

      - name: Publish npm package
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
